title: CosmoMathmo
theme: jekyll-theme-minimal
logo: /assets/img/ME3.jpeg
logo1: /assets/img/good_code.png
logo2: /assets/img/scientific_paper_graph_quality.png
logo3: /assets/img/teaching.png
logo4: /assets/img/questions.png
logo5: /assets/img/duck_alignment.jpg
description: Observational Cosmologist
google_analytics: UA-144586651-1
