title: CosmoMathmo
theme: jekyll-theme-minimal
logo: /assets/img/ME3.jpeg
logo1: /assets/img/good_code.png
logo2: /assets/img/scientific_paper_graph_quality.png
description: Observational Cosmologist
